name: Refresh workflow health CSV
on:
  schedule: [{ cron: "17 3 * * *" }]
  workflow_dispatch:
jobs:
  pull:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install requests
      - name: Pull runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/pull_workflow_runs.py
      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/ops/workflow_runs.csv
          git commit -m "chore(data): refresh workflow runs CSV" || echo "No changes"
          git push
